name: MacOS tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    linux:
        name: MacOS Py${{ matrix.PYTHON_VERSION }}
        runs-on: macos-latest
        env:
            PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
            RUNNER_OS: "macos"
        strategy:
            fail-fast: false
            matrix:
                PYTHON_VERSION: ["3.5", "3.6", "3.7", "3.8"]
        steps:
            - name: Install Conda
              uses: goanpeca/setup-miniconda@v1
              with:
                activate-environment: test
                auto-update-conda: true
                auto-activate-base: false
                python-version: ${{ matrix.PYTHON_VERSION }}
            - name: Install build/test dependencies
              shell: bash -l {0}
              run: pip install diff-match-patch
            - name: Run tests
              shell: bash -l {0}
              run: pytest -v -x --cov=three_merge three_merge/tests
